test_task:
  container:
    image: framgiaciteam/laravel:benmark
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn run test