version: 2
jobs:
  build:
    docker:
      - image: framgiaciteam/laravel:benmark
      - image: mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: homestead_test
          MYSQL_USER: homestead_test
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root

    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v3-{{ checksum "composer.lock" }}
      - run: composer install
      - save_cache:
          key: vendor-v3-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: php artisan config:clear
      - run: cat /etc/hosts && cat /etc/resolv.conf
      # node cache
      - restore_cache:
          keys:
            - node-modules-v3-{{ checksum "package-lock.json" }}
      - run: npm install node-sass
      - run: npm install
      - save_cache:
          key: node-modules-v3-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # run
      - run: framgia-ci test-connect 127.0.0.1 3306 80
      - run: framgia-ci run --local
